export const metadata = {
  title: 'About · BCH Cheat Sheet Generator',
};

export default function AboutPage() {
  return (
    <div className="mx-auto max-w-3xl px-6 py-8">
      <header className="mb-6">
        <h1 className="text-2xl font-bold tracking-tight text-bch-navy">About</h1>
      </header>

      <div className="space-y-6">
        <section className="card p-6">
          <h2 className="text-sm font-bold text-bch-navy">What this does</h2>
          <p className="mt-2 text-sm leading-relaxed">
            Upload a project&rsquo;s mechanical specifications — a whole division, a bound
            manual, or a folder of individual sections — and this works out what is in
            them, which trades they cover, and builds a cheat sheet for each: a dense
            reference of tables, matrices and callouts in BCH&rsquo;s house format.
          </p>
          <p className="mt-3 text-sm leading-relaxed">
            It is written for estimators first. What governs quantity, material and scope
            leads: size breaks, material by system and location, what is included and what
            is somebody else&rsquo;s, named products and their acceptable equals. Project
            managers and installing crews read the same sheet, so what governs how the
            work is built stays on it.
          </p>
          <p className="mt-3 text-sm leading-relaxed">
            Every sheet comes with a discrepancy log: every conflict, gap, overlap and
            ambiguity found in the specifications, ranked by what it costs to get wrong,
            with the reading the sheet was built on and what to do about it. Where two
            documents disagree, the more stringent requirement wins and the conflict is
            logged.
          </p>
        </section>

        <section className="card p-6">
          <h2 className="text-sm font-bold text-bch-navy">How it reads a specification</h2>
          <p className="mt-2 text-sm leading-relaxed">
            Each section is read on its own, one at a time, rather than the whole division
            at once. A single pass over a 250-page division skims whatever sits at the
            edges — on one real book a 48,000-character testing and balancing section was
            never used at all, and the sheet said nothing about it. Reading section by
            section removes the point at which coverage falls away.
          </p>
          <p className="mt-3 text-sm leading-relaxed">
            Those readings are then assembled into each sheet. Sections shared between
            trades — hangers, identification, testing and balancing — are read once and
            used by every sheet that needs them, which is why two sheets from one upload
            agree with each other.
          </p>
        </section>

        <section className="card border-red-200 bg-red-50 p-6">
          <h2 className="text-sm font-bold text-red-800">
            A quick reference, not a contract document
          </h2>
          <p className="mt-2 text-sm leading-relaxed text-red-900">
            The sheet does not replace, amend or govern the specification or the contract
            drawings, and nothing on it is a substitute for reading the section it came
            from.
          </p>
          <p className="mt-3 text-sm font-semibold text-red-900">
            Verify against full spec &amp; drawings.
          </p>
          <p className="mt-3 text-sm leading-relaxed text-red-900">
            Values are generated by reading the uploaded text and can be wrong, stale or
            incomplete — particularly where a section defers to a standard or a drawing.
            Read the discrepancy log before anyone prices or builds from a sheet.
          </p>
        </section>

        <section className="card p-6">
          <h2 className="text-sm font-bold text-bch-navy">Developed by</h2>
          <p className="mt-2 text-sm leading-relaxed">
            <b>Joshua Ahwai</b>
            <br />
            BCH Mechanical
          </p>
          <p className="mt-4 text-xs text-bch-muted">
            Designed and developed for BCH Mechanical, 2026.
          </p>
        </section>

        <section className="card p-6">
          <h2 className="text-sm font-bold text-bch-navy">Notes</h2>
          <ul className="mt-2 space-y-2 text-sm leading-relaxed text-bch-muted">
            <li>
              Past Jobs are stored in your browser only. They are not shared between
              machines or between people, and clearing your browser data removes them.
            </li>
            <li>
              Uploaded specifications are read to build the sheets and are not kept
              afterwards.
            </li>
            <li>
              Specifications only. Drawings are not read, so anything carried on a drawing
              or a schedule will be reported as missing rather than guessed at.
            </li>
            <li>
              Divisions 22 and 23 are read in full. Sections outside them that bear on the
              work are named to the tool as context; you can ask for any of them to be read
              properly before building, and the review screen prices each one.
            </li>
          </ul>
        </section>
      </div>
    </div>
  );
}
