export const metadata = {
  title: 'About · BCH Cheat Sheet Generator',
};

export default function AboutPage() {
  return (
    <div className="mx-auto max-w-3xl px-6 py-8">
      <header className="mb-6">
        <h1 className="text-2xl font-bold tracking-tight text-bch-navy">About</h1>
      </header>

      <div className="space-y-6">
        <section className="card p-6">
          <h2 className="text-sm font-bold text-bch-navy">What this does</h2>
          <p className="mt-2 text-sm leading-relaxed">
            Upload the specification sections for one division and this reads them, pulls
            out everything that changes what a fitter installs or orders — or what an
            estimator prices — and lays it out in BCH&rsquo;s house cheat-sheet format: a
            dense, three-to-five page field reference of tables, matrices, and callouts.
          </p>
          <p className="mt-3 text-sm leading-relaxed">
            Alongside it you get a verification checklist recording which sections were
            read, every conflict, gap, overlap, and ambiguity found in the specs, and how
            each conflict was resolved. Where two documents disagree, the more stringent
            requirement wins and the conflict is logged.
          </p>
        </section>

        <section className="card border-red-200 bg-red-50 p-6">
          <h2 className="text-sm font-bold text-red-800">
            This is a field reference, not a contract document
          </h2>
          <p className="mt-2 text-sm leading-relaxed text-red-900">
            The sheet is a quick reference. It does not replace, amend, or govern the
            specification or the contract drawings, and nothing on it is a substitute for
            reading the section it came from.
          </p>
          <p className="mt-3 text-sm font-semibold text-red-900">
            Verify against full spec &amp; drawings.
          </p>
          <p className="mt-3 text-sm leading-relaxed text-red-900">
            Values are generated by reading the uploaded text and can be wrong, stale, or
            incomplete — particularly where a section defers to a standard or a drawing.
            Read the checklist before anyone builds off the sheet.
          </p>
        </section>

        <section className="card p-6">
          <h2 className="text-sm font-bold text-bch-navy">Developed by</h2>
          <p className="mt-2 text-sm leading-relaxed">
            <b>Joshua Ahwai</b>
            <br />
            Assistant Project Manager Intern
            <br />
            BCH Mechanical
          </p>
          <p className="mt-4 text-xs text-bch-muted">
            Designed and developed for BCH Mechanical, 2026.
          </p>
        </section>

        <section className="card p-6">
          <h2 className="text-sm font-bold text-bch-navy">Notes</h2>
          <ul className="mt-2 space-y-2 text-sm leading-relaxed text-bch-muted">
            <li>
              Internal tool — no sign-in. Past Jobs are stored in your browser only and
              are not shared between machines or users.
            </li>
            <li>
              Uploaded specs are read to generate the sheet and are not retained after the
              request completes.
            </li>
            <li>Specs only. Drawings are not read.</li>
          </ul>
        </section>
      </div>
    </div>
  );
}
